# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NIMMuiscTeach' do
  pod 'NIMSDK', '~> 6.6.0'
  pod 'CocoaLumberjack', '~> 3.4.1'
  pod 'Toast', '~> 4.0.0'
  pod 'SVProgressHUD', '~> 2.2.2'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'RealReachability', '~>1.1.9'

end
